---
- name: Copy phpfile to webserver
  hosts: web
  become: true
  vars:
    file_src: /home/DevOps-M2-Task2/index.php
    file_dest: /var/www/html
  tasks:
    - name: Copy file
      copy:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
        
- name: Copy png to webserver
  hosts: web
  become: true
  vars:
    file_src: /home/DevOps-M2-Task2/bulgaria-map.png
    file_dest: /var/www/html
  tasks:
    - name: Copy file
      copy:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
