---
- name: Install and configure Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
        
----
- name: Install MariaDB
  hosts: db
  become: true

  tasks:
    - name: Install MariaDB
      apt:
        name:
          - mariadb-server
          - python3-pymysql
        state: present
