- name: Install MariaDB
  hosts: db
  become: true

  tasks:
    - name: Install MariaDB
      apt:
        name:
          - mariadb-client
          - mariadb-common
          - mariadb-server
        state: present
