- name: Install MySQL
  hosts: db
  become: true

  tasks:
    - name: Install MySQL
      yum:
        name:
          - python3-apt
          - mysql-server
          - python3-mysqldb
        state: present
