---
- name: Install and configure Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
              php
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
        
#- name: Copy phpfile to webserver
 # hosts: web
  #become: true
  #vars:
   # file_src: /home/
    #file_dest: /
 # tasks:
  #  - name: Copy file
   #   copy:
    #    src: "{{ file_src }}"
     #   dest: "{{ file_dest }}"
