- name: Install MariaDB
  hosts: db
  become: true

  tasks:
    - name: Install MariaDB
      yum:
        name:
           - mariadb-server
        state: present
       
  - name: Secure MariaDB installation
      mysql_user:
        name: vagrant
        password: "vagrant"
        host_all: yes
        login_unix_socket: /var/lib/mysql/mysql.sock
        state: present
        check_implicit_admin: yes

    - name: Create user and grant privileges
      mysql_user:
        name: vagrant
        password: "vagrant"
        priv: "vagrant.*:ALL"
        host: localhost
        state: present
